/**
 * ChromaShift Game - Board definitions
 * This file contains all the predefined board layouts and difficulty levels
 */

// Color constants (imported from main script)
const COLOR_RED = '#e74c3c';
const COLOR_BLUE = '#3498db';
const COLOR_YELLOW = '#f1c40f';
const COLOR_GREEN = '#2ecc71';
const COLOR_PURPLE = '#9b59b6';

// Board difficulty levels
const BoardDifficulty = {
  1: "קל מאוד",      // Very Easy
  2: "קל",           // Easy
  3: "קל-בינוני",    // Easy-Medium
  4: "בינוני",       // Medium
  5: "בינוני",       // Medium
  6: "בינוני-קשה",   // Medium-Hard
  7: "בינוני-קשה",   // Medium-Hard
  8: "קשה",          // Hard
  9: "קשה",          // Hard
  10: "קשה",         // Hard
  11: "קשה",         // Hard
  12: "קשה",         // Hard
  13: "קשה מאוד",    // Very Hard
  14: "קשה מאוד",    // Very Hard
  15: "קשה מאוד",    // Very Hard
  16: "קשה מאוד",    // Very Hard
  17: "מומחה",       // Expert
  18: "מומחה",       // Expert
  19: "מומחה",       // Expert
  20: "אלוף"         // Master
};

// Define all predefined board layouts
const PredefinedBoards = [
  // Board 1 - Very Easy: Large connected regions, only 3 colors
  [
    [COLOR_RED, COLOR_RED, COLOR_RED, COLOR_BLUE, COLOR_BLUE, COLOR_BLUE],
    [COLOR_RED, COLOR_RED, COLOR_RED, COLOR_BLUE, COLOR_BLUE, COLOR_BLUE],
    [COLOR_GREEN, COLOR_GREEN, COLOR_GREEN, COLOR_BLUE, COLOR_BLUE, COLOR_BLUE],
    [COLOR_GREEN, COLOR_GREEN, COLOR_GREEN, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW],
    [COLOR_GREEN, COLOR_GREEN, COLOR_GREEN, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW],
    [COLOR_RED, COLOR_RED, COLOR_RED, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW]
  ],

  // Board 2 - Easy: Medium islands, 4 colors
  [
    [COLOR_RED, COLOR_RED, COLOR_BLUE, COLOR_BLUE, COLOR_GREEN, COLOR_GREEN],
    [COLOR_RED, COLOR_RED, COLOR_BLUE, COLOR_BLUE, COLOR_GREEN, COLOR_GREEN],
    [COLOR_YELLOW, COLOR_YELLOW, COLOR_BLUE, COLOR_BLUE, COLOR_GREEN, COLOR_GREEN],
    [COLOR_YELLOW, COLOR_YELLOW, COLOR_PURPLE, COLOR_PURPLE, COLOR_GREEN, COLOR_GREEN],
    [COLOR_YELLOW, COLOR_YELLOW, COLOR_PURPLE, COLOR_PURPLE, COLOR_RED, COLOR_RED],
    [COLOR_YELLOW, COLOR_YELLOW, COLOR_PURPLE, COLOR_PURPLE, COLOR_RED, COLOR_RED]
  ],

  // Board 3 - Easy-Medium: Some structure but more fragmented
  [
    [COLOR_RED, COLOR_RED, COLOR_BLUE, COLOR_GREEN, COLOR_GREEN, COLOR_PURPLE],
    [COLOR_RED, COLOR_RED, COLOR_BLUE, COLOR_BLUE, COLOR_GREEN, COLOR_PURPLE],
    [COLOR_YELLOW, COLOR_YELLOW, COLOR_BLUE, COLOR_BLUE, COLOR_GREEN, COLOR_PURPLE],
    [COLOR_YELLOW, COLOR_YELLOW, COLOR_PURPLE, COLOR_GREEN, COLOR_GREEN, COLOR_PURPLE],
    [COLOR_RED, COLOR_YELLOW, COLOR_PURPLE, COLOR_PURPLE, COLOR_BLUE, COLOR_BLUE],
    [COLOR_RED, COLOR_RED, COLOR_PURPLE, COLOR_YELLOW, COLOR_BLUE, COLOR_BLUE]
  ],

  // Board 4 - Medium: Smaller connected regions, all 5 colors
  [
    [COLOR_RED, COLOR_BLUE, COLOR_BLUE, COLOR_GREEN, COLOR_PURPLE, COLOR_PURPLE],
    [COLOR_RED, COLOR_RED, COLOR_BLUE, COLOR_GREEN, COLOR_GREEN, COLOR_PURPLE],
    [COLOR_YELLOW, COLOR_RED, COLOR_BLUE, COLOR_BLUE, COLOR_GREEN, COLOR_PURPLE],
    [COLOR_YELLOW, COLOR_YELLOW, COLOR_RED, COLOR_GREEN, COLOR_GREEN, COLOR_PURPLE],
    [COLOR_PURPLE, COLOR_YELLOW, COLOR_RED, COLOR_RED, COLOR_BLUE, COLOR_BLUE],
    [COLOR_PURPLE, COLOR_PURPLE, COLOR_YELLOW, COLOR_RED, COLOR_BLUE, COLOR_YELLOW]
  ],

  // Board 5 - Medium: All colors, strategic placement
  [
    [COLOR_RED, COLOR_BLUE, COLOR_YELLOW, COLOR_GREEN, COLOR_BLUE, COLOR_RED],
    [COLOR_BLUE, COLOR_RED, COLOR_GREEN, COLOR_YELLOW, COLOR_RED, COLOR_BLUE],
    [COLOR_YELLOW, COLOR_GREEN, COLOR_BLUE, COLOR_RED, COLOR_PURPLE, COLOR_YELLOW],
    [COLOR_GREEN, COLOR_YELLOW, COLOR_RED, COLOR_PURPLE, COLOR_BLUE, COLOR_GREEN],
    [COLOR_PURPLE, COLOR_PURPLE, COLOR_PURPLE, COLOR_GREEN, COLOR_YELLOW, COLOR_RED],
    [COLOR_RED, COLOR_BLUE, COLOR_YELLOW, COLOR_GREEN, COLOR_PURPLE, COLOR_BLUE]
  ],

  // Board 6 - Medium-Hard: More complex pattern
  [
    [COLOR_RED, COLOR_BLUE, COLOR_GREEN, COLOR_YELLOW, COLOR_PURPLE, COLOR_BLUE],
    [COLOR_PURPLE, COLOR_RED, COLOR_BLUE, COLOR_GREEN, COLOR_YELLOW, COLOR_RED],
    [COLOR_YELLOW, COLOR_PURPLE, COLOR_RED, COLOR_BLUE, COLOR_GREEN, COLOR_PURPLE],
    [COLOR_GREEN, COLOR_YELLOW, COLOR_PURPLE, COLOR_RED, COLOR_BLUE, COLOR_YELLOW],
    [COLOR_BLUE, COLOR_GREEN, COLOR_YELLOW, COLOR_PURPLE, COLOR_RED, COLOR_GREEN],
    [COLOR_RED, COLOR_BLUE, COLOR_GREEN, COLOR_YELLOW, COLOR_PURPLE, COLOR_RED]
  ],

  // Board 7 - Medium-Hard: Limited adjacent matching colors
  [
    [COLOR_RED, COLOR_BLUE, COLOR_GREEN, COLOR_YELLOW, COLOR_PURPLE, COLOR_RED],
    [COLOR_YELLOW, COLOR_PURPLE, COLOR_RED, COLOR_BLUE, COLOR_GREEN, COLOR_YELLOW],
    [COLOR_GREEN, COLOR_RED, COLOR_YELLOW, COLOR_PURPLE, COLOR_BLUE, COLOR_GREEN],
    [COLOR_BLUE, COLOR_YELLOW, COLOR_PURPLE, COLOR_RED, COLOR_GREEN, COLOR_BLUE],
    [COLOR_PURPLE, COLOR_GREEN, COLOR_BLUE, COLOR_YELLOW, COLOR_RED, COLOR_PURPLE],
    [COLOR_RED, COLOR_BLUE, COLOR_GREEN, COLOR_YELLOW, COLOR_PURPLE, COLOR_GREEN]
  ],

  // Board 8 - Hard: Few adjacent same colors
  [
    [COLOR_RED, COLOR_BLUE, COLOR_GREEN, COLOR_PURPLE, COLOR_YELLOW, COLOR_RED],
    [COLOR_GREEN, COLOR_YELLOW, COLOR_PURPLE, COLOR_RED, COLOR_BLUE, COLOR_GREEN],
    [COLOR_BLUE, COLOR_PURPLE, COLOR_RED, COLOR_YELLOW, COLOR_GREEN, COLOR_BLUE],
    [COLOR_YELLOW, COLOR_RED, COLOR_BLUE, COLOR_GREEN, COLOR_PURPLE, COLOR_YELLOW],
    [COLOR_PURPLE, COLOR_GREEN, COLOR_YELLOW, COLOR_BLUE, COLOR_RED, COLOR_PURPLE],
    [COLOR_RED, COLOR_BLUE, COLOR_GREEN, COLOR_PURPLE, COLOR_YELLOW, COLOR_BLUE]
  ],

  // Board 9 - Hard: Strategic color distribution
  [
    [COLOR_GREEN, COLOR_YELLOW, COLOR_PURPLE, COLOR_RED, COLOR_BLUE, COLOR_GREEN],
    [COLOR_BLUE, COLOR_PURPLE, COLOR_RED, COLOR_YELLOW, COLOR_GREEN, COLOR_RED],
    [COLOR_YELLOW, COLOR_RED, COLOR_BLUE, COLOR_GREEN, COLOR_PURPLE, COLOR_BLUE],
    [COLOR_PURPLE, COLOR_GREEN, COLOR_YELLOW, COLOR_BLUE, COLOR_RED, COLOR_YELLOW],
    [COLOR_RED, COLOR_BLUE, COLOR_GREEN, COLOR_PURPLE, COLOR_YELLOW, COLOR_PURPLE],
    [COLOR_GREEN, COLOR_YELLOW, COLOR_PURPLE, COLOR_RED, COLOR_BLUE, COLOR_RED]
  ],

  // Board 10 - Hard: Checkerboard-like pattern
  [
    [COLOR_RED, COLOR_BLUE, COLOR_RED, COLOR_BLUE, COLOR_RED, COLOR_BLUE],
    [COLOR_GREEN, COLOR_YELLOW, COLOR_GREEN, COLOR_YELLOW, COLOR_GREEN, COLOR_YELLOW],
    [COLOR_PURPLE, COLOR_RED, COLOR_PURPLE, COLOR_RED, COLOR_PURPLE, COLOR_RED],
    [COLOR_BLUE, COLOR_GREEN, COLOR_BLUE, COLOR_GREEN, COLOR_BLUE, COLOR_GREEN],
    [COLOR_YELLOW, COLOR_PURPLE, COLOR_YELLOW, COLOR_PURPLE, COLOR_YELLOW, COLOR_PURPLE],
    [COLOR_RED, COLOR_BLUE, COLOR_RED, COLOR_BLUE, COLOR_RED, COLOR_BLUE]
  ],

  // Board 11 - Hard: Interlocking paths
  [
    [COLOR_RED, COLOR_RED, COLOR_BLUE, COLOR_BLUE, COLOR_GREEN, COLOR_RED],
    [COLOR_PURPLE, COLOR_YELLOW, COLOR_GREEN, COLOR_PURPLE, COLOR_GREEN, COLOR_RED],
    [COLOR_PURPLE, COLOR_YELLOW, COLOR_BLUE, COLOR_PURPLE, COLOR_BLUE, COLOR_BLUE],
    [COLOR_YELLOW, COLOR_YELLOW, COLOR_BLUE, COLOR_RED, COLOR_BLUE, COLOR_GREEN],
    [COLOR_RED, COLOR_PURPLE, COLOR_GREEN, COLOR_RED, COLOR_YELLOW, COLOR_GREEN],
    [COLOR_RED, COLOR_PURPLE, COLOR_GREEN, COLOR_RED, COLOR_YELLOW, COLOR_PURPLE]
  ],

  // Board 12 - Hard: Complex pattern with minimal adjacency
  [
    [COLOR_RED, COLOR_BLUE, COLOR_GREEN, COLOR_PURPLE, COLOR_YELLOW, COLOR_BLUE],
    [COLOR_YELLOW, COLOR_PURPLE, COLOR_RED, COLOR_BLUE, COLOR_GREEN, COLOR_RED],
    [COLOR_GREEN, COLOR_RED, COLOR_YELLOW, COLOR_GREEN, COLOR_PURPLE, COLOR_YELLOW],
    [COLOR_BLUE, COLOR_GREEN, COLOR_PURPLE, COLOR_RED, COLOR_BLUE, COLOR_GREEN],
    [COLOR_PURPLE, COLOR_BLUE, COLOR_RED, COLOR_YELLOW, COLOR_RED, COLOR_PURPLE],
    [COLOR_RED, COLOR_YELLOW, COLOR_GREEN, COLOR_BLUE, COLOR_PURPLE, COLOR_YELLOW]
  ],

  // Board 13 - Very Hard: Spiral pattern
  [
    [COLOR_RED, COLOR_GREEN, COLOR_BLUE, COLOR_YELLOW, COLOR_PURPLE, COLOR_GREEN],
    [COLOR_PURPLE, COLOR_YELLOW, COLOR_RED, COLOR_GREEN, COLOR_BLUE, COLOR_RED],
    [COLOR_BLUE, COLOR_PURPLE, COLOR_YELLOW, COLOR_RED, COLOR_GREEN, COLOR_YELLOW],
    [COLOR_GREEN, COLOR_BLUE, COLOR_PURPLE, COLOR_YELLOW, COLOR_RED, COLOR_PURPLE],
    [COLOR_RED, COLOR_GREEN, COLOR_BLUE, COLOR_PURPLE, COLOR_YELLOW, COLOR_BLUE],
    [COLOR_YELLOW, COLOR_RED, COLOR_GREEN, COLOR_BLUE, COLOR_PURPLE, COLOR_RED]
  ],

  // Board 14 - Very Hard: Alternating diagonals
  [
    [COLOR_RED, COLOR_BLUE, COLOR_RED, COLOR_GREEN, COLOR_YELLOW, COLOR_PURPLE],
    [COLOR_BLUE, COLOR_RED, COLOR_GREEN, COLOR_YELLOW, COLOR_PURPLE, COLOR_BLUE],
    [COLOR_RED, COLOR_GREEN, COLOR_YELLOW, COLOR_PURPLE, COLOR_BLUE, COLOR_RED],
    [COLOR_GREEN, COLOR_YELLOW, COLOR_PURPLE, COLOR_BLUE, COLOR_RED, COLOR_GREEN],
    [COLOR_YELLOW, COLOR_PURPLE, COLOR_BLUE, COLOR_RED, COLOR_GREEN, COLOR_YELLOW],
    [COLOR_PURPLE, COLOR_BLUE, COLOR_RED, COLOR_GREEN, COLOR_YELLOW, COLOR_PURPLE]
  ],

  // Board 15 - Very Hard: Advanced strategic layout
  [
    [COLOR_RED, COLOR_BLUE, COLOR_GREEN, COLOR_PURPLE, COLOR_YELLOW, COLOR_RED],
    [COLOR_PURPLE, COLOR_GREEN, COLOR_BLUE, COLOR_RED, COLOR_YELLOW, COLOR_GREEN],
    [COLOR_YELLOW, COLOR_RED, COLOR_PURPLE, COLOR_GREEN, COLOR_BLUE, COLOR_YELLOW],
    [COLOR_BLUE, COLOR_YELLOW, COLOR_RED, COLOR_PURPLE, COLOR_GREEN, COLOR_BLUE],
    [COLOR_GREEN, COLOR_PURPLE, COLOR_YELLOW, COLOR_BLUE, COLOR_RED, COLOR_PURPLE],
    [COLOR_RED, COLOR_BLUE, COLOR_GREEN, COLOR_YELLOW, COLOR_PURPLE, COLOR_GREEN]
  ],

  // Board 16 - Very Hard: Intricate color maze
  [
    [COLOR_PURPLE, COLOR_YELLOW, COLOR_RED, COLOR_GREEN, COLOR_BLUE, COLOR_RED],
    [COLOR_GREEN, COLOR_BLUE, COLOR_PURPLE, COLOR_YELLOW, COLOR_RED, COLOR_PURPLE],
    [COLOR_RED, COLOR_GREEN, COLOR_BLUE, COLOR_PURPLE, COLOR_YELLOW, COLOR_BLUE],
    [COLOR_YELLOW, COLOR_RED, COLOR_GREEN, COLOR_BLUE, COLOR_PURPLE, COLOR_GREEN],
    [COLOR_BLUE, COLOR_PURPLE, COLOR_YELLOW, COLOR_RED, COLOR_GREEN, COLOR_YELLOW],
    [COLOR_GREEN, COLOR_BLUE, COLOR_PURPLE, COLOR_YELLOW, COLOR_RED, COLOR_PURPLE]
  ],

  // Board 17 - Expert: Maximum difficulty, strategic capture paths
  [
    [COLOR_RED, COLOR_BLUE, COLOR_YELLOW, COLOR_GREEN, COLOR_PURPLE, COLOR_BLUE],
    [COLOR_GREEN, COLOR_PURPLE, COLOR_RED, COLOR_BLUE, COLOR_YELLOW, COLOR_PURPLE],
    [COLOR_BLUE, COLOR_RED, COLOR_GREEN, COLOR_PURPLE, COLOR_RED, COLOR_YELLOW],
    [COLOR_YELLOW, COLOR_GREEN, COLOR_PURPLE, COLOR_RED, COLOR_GREEN, COLOR_BLUE],
    [COLOR_PURPLE, COLOR_BLUE, COLOR_YELLOW, COLOR_GREEN, COLOR_BLUE, COLOR_RED],
    [COLOR_RED, COLOR_YELLOW, COLOR_BLUE, COLOR_PURPLE, COLOR_YELLOW, COLOR_GREEN]
  ],

  // Board 18 - Expert: Cross-board strategy required
  [
    [COLOR_RED, COLOR_GREEN, COLOR_BLUE, COLOR_YELLOW, COLOR_PURPLE, COLOR_RED],
    [COLOR_YELLOW, COLOR_PURPLE, COLOR_RED, COLOR_GREEN, COLOR_BLUE, COLOR_YELLOW],
    [COLOR_BLUE, COLOR_RED, COLOR_YELLOW, COLOR_PURPLE, COLOR_RED, COLOR_GREEN],
    [COLOR_GREEN, COLOR_BLUE, COLOR_PURPLE, COLOR_RED, COLOR_YELLOW, COLOR_BLUE],
    [COLOR_PURPLE, COLOR_YELLOW, COLOR_GREEN, COLOR_BLUE, COLOR_GREEN, COLOR_PURPLE],
    [COLOR_RED, COLOR_GREEN, COLOR_BLUE, COLOR_YELLOW, COLOR_PURPLE, COLOR_RED]
  ],

  // Board 19 - Expert: Complex island hopping pattern
  [
    [COLOR_RED, COLOR_BLUE, COLOR_GREEN, COLOR_PURPLE, COLOR_YELLOW, COLOR_RED],
    [COLOR_PURPLE, COLOR_YELLOW, COLOR_RED, COLOR_BLUE, COLOR_GREEN, COLOR_BLUE],
    [COLOR_GREEN, COLOR_RED, COLOR_PURPLE, COLOR_YELLOW, COLOR_BLUE, COLOR_PURPLE],
    [COLOR_BLUE, COLOR_GREEN, COLOR_YELLOW, COLOR_RED, COLOR_PURPLE, COLOR_GREEN],
    [COLOR_YELLOW, COLOR_PURPLE, COLOR_BLUE, COLOR_GREEN, COLOR_RED, COLOR_YELLOW],
    [COLOR_RED, COLOR_BLUE, COLOR_GREEN, COLOR_PURPLE, COLOR_YELLOW, COLOR_BLUE]
  ],

  // Board 20 - Master: Ultimate challenge
  [
    [COLOR_RED, COLOR_BLUE, COLOR_YELLOW, COLOR_GREEN, COLOR_PURPLE, COLOR_RED],
    [COLOR_PURPLE, COLOR_RED, COLOR_BLUE, COLOR_YELLOW, COLOR_GREEN, COLOR_BLUE],
    [COLOR_YELLOW, COLOR_PURPLE, COLOR_RED, COLOR_BLUE, COLOR_YELLOW, COLOR_YELLOW],
    [COLOR_GREEN, COLOR_YELLOW, COLOR_PURPLE, COLOR_RED, COLOR_BLUE, COLOR_GREEN],
    [COLOR_BLUE, COLOR_GREEN, COLOR_YELLOW, COLOR_PURPLE, COLOR_RED, COLOR_PURPLE],
    [COLOR_RED, COLOR_BLUE, COLOR_GREEN, COLOR_YELLOW, COLOR_PURPLE, COLOR_RED]
  ]
];

// Export the board definitions and difficulty levels
export { PredefinedBoards, BoardDifficulty };